language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/sevki.org/q9p"
  - go get -v -t -d sevki.org/q9p/...
script:
  - go test sevki.org/q9p/...
